# Generated by Django 6.1.1 on 2026-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
