# Generated by Django 6.1.1 on 2026-09-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0003_alter_unit_monthly_rent'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='lease_end_date_after_start_date'),
        ),
    ]
