# Generated by Django 6.1.1 on 2026-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_lease_lease_end_date_after_start_date'),
        ('properties', '0003_alter_unit_monthly_rent'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lease',
            name='max_installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('max_installments__gte', 1)), name='lease_max_installments_positive'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 28)), name='lease_due_day_valid'),
        ),
    ]
