# Generated by Django 6.1.1 on 2026-09-15 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_due_day_lease_max_installments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rents', to='leases.lease')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lease', 'period'), name='unique_rent_per_lease_period'), models.CheckConstraint(condition=models.Q(('amount_due__gt', 0)), name='rent_amount_due_positive')],
            },
        ),
    ]
